### ISSUE TITLE
Missing method: merge()

### ISSUE THREAD

**Issue by donquixote** [ericmorand/drupal-attribute#15]
In Drupal, the Attribute class has a 'merge' method.
This is currently the only way to achieve immutable operations:
See https://www.drupal.org/project/drupal/issues/3296456#comment-14609720

Here in the js version, only few methods are implemented. merge() is not among them.

**Comment by tibi2303** [comment]
https://github.com/ericmorand/drupal-attribute/pull/16

**Comment by ericmorand** [comment]
Available in 1.1.0. Thanks guys.
